# This is a basic workflow that is manually triggered

name: Retire workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploymyapp:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: cat /etc/os-release
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.0

    - run: npm install
    - run: npm install -g retire
    - run: retire -v >> retire.txt
    - name: Upload Retire output for deployment job
      uses: actions/upload-artifact@v3
      with:
          name: retire results
          path: retire.txt
    - name: Build
      if: always()
      run: npm run build


    - name: ssh-scp-deploy
      if: always()
    # You may pin to the exact commit or the version.
    # uses: marcodallasanta/ssh-scp-deploy@acf9c1fefcda34c0b8b0cb0c0c1b521bf130d8b6
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
          # Local file path
        local: ./public
        remote:  /home/madan/public
        host: 20.51.253.91
        user: madan
        key: ${{ secrets.SSH_KEY }}  
        pre_upload: rm -rf /home/madan/public
        post_upload: sudo cp -r public/* /var/www/html
        scp_options: -r
